/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "target/rust-test.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_rust_1test_1cJNI_CResponse_1Response_1ok_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  CResponse_Response *arg1 = (CResponse_Response *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CResponse_Response **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->ok = arg2;
}


SWIGEXPORT jboolean JNICALL Java_rust_1test_1cJNI_CResponse_1Response_1ok_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  CResponse_Response *arg1 = (CResponse_Response *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CResponse_Response **)&jarg1; 
  result = (bool) ((arg1)->ok);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rust_1test_1cJNI_CResponse_1Response_1response_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  CResponse_Response *arg1 = (CResponse_Response *) 0 ;
  Response arg2 ;
  Response *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CResponse_Response **)&jarg1; 
  argp2 = *(Response **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Response");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->response = arg2;
}


SWIGEXPORT jlong JNICALL Java_rust_1test_1cJNI_CResponse_1Response_1response_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  CResponse_Response *arg1 = (CResponse_Response *) 0 ;
  Response result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CResponse_Response **)&jarg1; 
  result =  ((arg1)->response);
  {
    Response * resultptr = (Response *) malloc(sizeof(Response));
    memmove(resultptr, &result, sizeof(Response));
    *(Response **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_rust_1test_1cJNI_CResponse_1Response_1error_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  CResponse_Response *arg1 = (CResponse_Response *) 0 ;
  String arg2 ;
  String *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CResponse_Response **)&jarg1; 
  argp2 = *(String **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null String");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT jlong JNICALL Java_rust_1test_1cJNI_CResponse_1Response_1error_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  CResponse_Response *arg1 = (CResponse_Response *) 0 ;
  String result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CResponse_Response **)&jarg1; 
  result =  ((arg1)->error);
  {
    String * resultptr = (String *) malloc(sizeof(String));
    memmove(resultptr, &result, sizeof(String));
    *(String **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rust_1test_1cJNI_new_1CResponse_1Response(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CResponse_Response *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CResponse_Response *)calloc(1, sizeof(CResponse_Response));
  *(CResponse_Response **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rust_1test_1cJNI_delete_1CResponse_1Response(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CResponse_Response *arg1 = (CResponse_Response *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CResponse_Response **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_rust_1test_1cJNI_execute(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_) {
  TestEngine *arg1 = (TestEngine *) 0 ;
  str *arg2 = (str *) 0 ;
  CResponse_Response *arg3 = (CResponse_Response *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(TestEngine **)&jarg1; 
  arg2 = *(str **)&jarg2; 
  arg3 = *(CResponse_Response **)&jarg3; 
  execute(arg1,(str const *)arg2,arg3);
}


SWIGEXPORT void JNICALL Java_rust_1test_1cJNI_handle_1event(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_) {
  TestEngine *arg1 = (TestEngine *) 0 ;
  CycleEvent *arg2 = (CycleEvent *) 0 ;
  CResponse_Response *arg3 = (CResponse_Response *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(TestEngine **)&jarg1; 
  arg2 = *(CycleEvent **)&jarg2; 
  arg3 = *(CResponse_Response **)&jarg3; 
  handle_event(arg1,(CycleEvent const *)arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_rust_1test_1cJNI_initial_1html(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  TestEngine *arg1 = (TestEngine *) 0 ;
  String result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(TestEngine **)&jarg1; 
  result = initial_html(arg1);
  {
    String * resultptr = (String *) malloc(sizeof(String));
    memmove(resultptr, &result, sizeof(String));
    *(String **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_rust_1test_1cJNI_make_1engine(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  TestEngine *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (TestEngine *)make_engine();
  *(TestEngine **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_rust_1test_1cJNI_set_1options(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  TestEngine *arg1 = (TestEngine *) 0 ;
  str *arg2 = (str *) 0 ;
  CResponse *arg3 = (CResponse *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(TestEngine **)&jarg1; 
  arg2 = *(str **)&jarg2; 
  arg3 = *(CResponse **)&jarg3; 
  set_options(arg1,(str const *)arg2,arg3);
}


#ifdef __cplusplus
}
#endif

