/* This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class rust_test_cJNI {
  public final static native void CResponse_Response_ok_set(long jarg1, CResponse_Response jarg1_, boolean jarg2);
  public final static native boolean CResponse_Response_ok_get(long jarg1, CResponse_Response jarg1_);
  public final static native void CResponse_Response_response_set(long jarg1, CResponse_Response jarg1_, long jarg2);
  public final static native long CResponse_Response_response_get(long jarg1, CResponse_Response jarg1_);
  public final static native void CResponse_Response_error_set(long jarg1, CResponse_Response jarg1_, long jarg2);
  public final static native long CResponse_Response_error_get(long jarg1, CResponse_Response jarg1_);
  public final static native long new_CResponse_Response();
  public final static native void delete_CResponse_Response(long jarg1);
  public final static native void execute(long jarg1, long jarg2, long jarg3, CResponse_Response jarg3_);
  public final static native void handle_event(long jarg1, long jarg2, long jarg3, CResponse_Response jarg3_);
  public final static native long initial_html(long jarg1);
  public final static native long make_engine();
  public final static native void set_options(long jarg1, long jarg2, long jarg3);
}
