/* This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class rust_test_c {
  public static void execute(SWIGTYPE_p_TestEngine engine, SWIGTYPE_p_str body, CResponse_Response resp) {
    rust_test_cJNI.execute(SWIGTYPE_p_TestEngine.getCPtr(engine), SWIGTYPE_p_str.getCPtr(body), CResponse_Response.getCPtr(resp), resp);
  }

  public static void handle_event(SWIGTYPE_p_TestEngine engine, SWIGTYPE_p_CycleEvent event, CResponse_Response resp) {
    rust_test_cJNI.handle_event(SWIGTYPE_p_TestEngine.getCPtr(engine), SWIGTYPE_p_CycleEvent.getCPtr(event), CResponse_Response.getCPtr(resp), resp);
  }

  public static SWIGTYPE_p_String initial_html(SWIGTYPE_p_TestEngine engine) {
    return new SWIGTYPE_p_String(rust_test_cJNI.initial_html(SWIGTYPE_p_TestEngine.getCPtr(engine)), true);
  }

  public static SWIGTYPE_p_TestEngine make_engine() {
    long cPtr = rust_test_cJNI.make_engine();
    return (cPtr == 0) ? null : new SWIGTYPE_p_TestEngine(cPtr, false);
  }

  public static void set_options(SWIGTYPE_p_TestEngine engine, SWIGTYPE_p_str options_json, SWIGTYPE_p_CResponse resp) {
    rust_test_cJNI.set_options(SWIGTYPE_p_TestEngine.getCPtr(engine), SWIGTYPE_p_str.getCPtr(options_json), SWIGTYPE_p_CResponse.getCPtr(resp));
  }

}
