/* This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package taiposwig;

public final class CCycleEvent {
  public final static CCycleEvent Start = new CCycleEvent("Start");
  public final static CCycleEvent Pause = new CCycleEvent("Pause");
  public final static CCycleEvent Resume = new CCycleEvent("Resume");
  public final static CCycleEvent Stop = new CCycleEvent("Stop");
  public final static CCycleEvent StopPC = new CCycleEvent("StopPC");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CCycleEvent swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CCycleEvent.class + " with value " + swigValue);
  }

  private CCycleEvent(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CCycleEvent(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CCycleEvent(String swigName, CCycleEvent swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CCycleEvent[] swigValues = { Start, Pause, Resume, Stop, StopPC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

