/* This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package taiposwig;

public class CResponseItem {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CResponseItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CResponseItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        taiposwigJNI.delete_CResponseItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKey(String value) {
    taiposwigJNI.CResponseItem_key_set(swigCPtr, this, value);
  }

  public String getKey() {
    return taiposwigJNI.CResponseItem_key_get(swigCPtr, this);
  }

  public void setValue(String value) {
    taiposwigJNI.CResponseItem_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return taiposwigJNI.CResponseItem_value_get(swigCPtr, this);
  }

  public CResponseItem() {
    this(taiposwigJNI.new_CResponseItem(), true);
  }

}
