/* This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package taiposwig;

public class taiposwig {
  public static void delete_data(SWIGTYPE_p_LowuData data) {
    taiposwigJNI.delete_data(SWIGTYPE_p_LowuData.getCPtr(data));
  }

  public static void execute(SWIGTYPE_p_LowuData data, String body) {
    taiposwigJNI.execute(SWIGTYPE_p_LowuData.getCPtr(data), body);
  }

  public static void handle_event(SWIGTYPE_p_LowuData data, CCycleEvent event) {
    taiposwigJNI.handle_event(SWIGTYPE_p_LowuData.getCPtr(data), event.swigValue());
  }

  public static String initial_html(SWIGTYPE_p_LowuData data) {
    return taiposwigJNI.initial_html(SWIGTYPE_p_LowuData.getCPtr(data));
  }

  public static boolean is_shutdown_required(SWIGTYPE_p_LowuData data) {
    return taiposwigJNI.is_shutdown_required(SWIGTYPE_p_LowuData.getCPtr(data));
  }

  public static SWIGTYPE_p_LowuData make_data(String fanling_options_json_c) {
    long cPtr = taiposwigJNI.make_data(fanling_options_json_c);
    return (cPtr == 0) ? null : new SWIGTYPE_p_LowuData(cPtr, false);
  }

  public static String response_error(SWIGTYPE_p_LowuData data) {
    return taiposwigJNI.response_error(SWIGTYPE_p_LowuData.getCPtr(data));
  }

  public static CResponseItem response_item(SWIGTYPE_p_LowuData data, int n) {
    return new CResponseItem(taiposwigJNI.response_item(SWIGTYPE_p_LowuData.getCPtr(data), n), true);
  }

  public static int response_num_items(SWIGTYPE_p_LowuData data) {
    return taiposwigJNI.response_num_items(SWIGTYPE_p_LowuData.getCPtr(data));
  }

  public static boolean response_ok(SWIGTYPE_p_LowuData data) {
    return taiposwigJNI.response_ok(SWIGTYPE_p_LowuData.getCPtr(data));
  }

}
